"""make organizer_id nullable

Revision ID: 40b5f17da8ad
Revises: a43d9dee2970
Create Date: 2026-07-06 14:24:18.541788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b5f17da8ad'
down_revision: Union[str, None] = 'a43d9dee2970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_code_key', 'events', type_='unique')
    op.drop_index('ix_events_date', table_name='events')
    op.create_index(op.f('ix_events_code'), 'events', ['code'], unique=True)
    op.drop_index('ix_user_register_gender', table_name='user_register')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_register_gender', 'user_register', ['gender'], unique=False)
    op.drop_index(op.f('ix_events_code'), table_name='events')
    op.create_index('ix_events_date', 'events', ['date'], unique=False)
    op.create_unique_constraint('events_code_key', 'events', ['code'])
    # ### end Alembic commands ###
