"""add detected face table and rename the event photos's attr name

Revision ID: 91108f2a3373
Revises: a38511a46f40
Create Date: 2026-07-23 15:55:04.860753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91108f2a3373'
down_revision: Union[str, None] = 'a38511a46f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_faces',
    sa.Column('detected_face_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_photo_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_photo_id'], ['event_photos.event_photo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_user_id'], ['user_register.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('detected_face_id')
    )
    op.create_index(op.f('ix_detected_faces_event_photo_id'), 'detected_faces', ['event_photo_id'], unique=False)
    op.create_index(op.f('ix_detected_faces_matched_user_id'), 'detected_faces', ['matched_user_id'], unique=False)
    op.add_column('event_photos', sa.Column('photo_type', sa.String(), nullable=False))
    op.add_column('event_photos', sa.Column('uploaded_user_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_event_photos_user_id', table_name='event_photos')
    op.create_index(op.f('ix_event_photos_uploaded_user_id'), 'event_photos', ['uploaded_user_id'], unique=False)
    op.drop_constraint('event_photos_user_id_fkey', 'event_photos', type_='foreignkey')
    op.create_foreign_key(None, 'event_photos', 'user_register', ['uploaded_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('event_photos', 'file_name')
    op.drop_column('event_photos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_photos', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('event_photos', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_photos', type_='foreignkey')
    op.create_foreign_key('event_photos_user_id_fkey', 'event_photos', 'user_register', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_event_photos_uploaded_user_id'), table_name='event_photos')
    op.create_index('ix_event_photos_user_id', 'event_photos', ['user_id'], unique=False)
    op.drop_column('event_photos', 'uploaded_user_id')
    op.drop_column('event_photos', 'photo_type')
    op.drop_index(op.f('ix_detected_faces_matched_user_id'), table_name='detected_faces')
    op.drop_index(op.f('ix_detected_faces_event_photo_id'), table_name='detected_faces')
    op.drop_table('detected_faces')
    # ### end Alembic commands ###
