"""add embedding column to profile_photo

Revision ID: a38511a46f40
Revises: 40b5f17da8ad
Create Date: 2026-07-22 17:58:48.839587

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38511a46f40'
down_revision: Union[str, None] = '40b5f17da8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     op.execute("CREATE EXTENSION IF NOT EXISTS vector")
#     op.add_column('profile_photo', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'profile_photo',
        sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_photo', 'embedding')
    # ### end Alembic commands ###

# def downgrade() -> None:
#     op.drop_constraint(None, 'profile_photo')
#     op.drop_column('profile_photo', 'embedding')
