"""make organizer_id nullable

Revision ID: a43d9dee2970
Revises: 
Create Date: 2026-07-06 13:59:14.882637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43d9dee2970'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'organizer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_events_code', table_name='events')
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_unique_constraint(None, 'events', ['code'])
    op.create_index(op.f('ix_user_register_gender'), 'user_register', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_register_gender'), table_name='user_register')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.create_index('ix_events_code', 'events', ['code'], unique=True)
    op.alter_column('events', 'organizer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
